# Since update v1.5.0 all configs has one version. If the version is changed, all config files are copied and moved
# to the "RandomLootChest/old" directory, new files are loaded, so if there is a new change, all data are copied
# and saved to this directory. Version of configs are changed, when new option is added and this option is
# needed to work, otherwise nothing happens. Don't change on your own!
config-version: 1

# Opens random chest
random-chests: false

# If chest is filled, the information is send to the player. Here you can choose how players
# recive the information about filled chest. You can choose all the options or disable them.
filled-chest-info:
  actionbar: true
  title: false
  chat: false

# If you have your old own cooldowns and you don't trust enough about new system,
# just switch this option to true.
old-cooldown-parse: false

# Currently, this option works only with HolographicDisplays - it sends hologram with information about the cooldown
holograms-on-chests: false

# When player is in Combat (CombatLogX), he cannot open any chest.
openchest-in-combat: false

chest-add-sound: ENTITY_EXPERIENCE_ORB_PICKUP

# In database, this plugin saves information about cooldowns to chests. If it is disabled, all cooldowns after reload plugin
# or server shutdown, will disappear.
database:
  use: false
  type: "YAML"
  #in seconds
  auto-save-time: 300
  host: "localhost"
  user: "user"
  password: "password"
  database: "database"
  port: 3306

wand-item:
  displayName: '&6Chest Wand'
  permission-to-use: true
