# Chest's title - nothing special, since mc 1.16 you can use hex colours!
Title: 'Default Chest'
# Since 1.5.0 there is new cooldown format, where you can put seconds, minutes, days, etc.
Cooldown: 30 seconds
# Max items in the chest
MaxItems: 4
# Max items in the same type in the chest is useful, when you have several items in the same type (20 gold ingots, 15 gold ingots, etc.)
MaxItemsInTheSameType: 1
# Particles above the chests.
# If you are using versions 1.9+, use this link: https://spigotdocs.okaeri.cloud/1.9.4/org/bukkit/Particle.html or newer docs
# But if you are using versions 1.7-1.8.9, use this link: https://spigotdocs.okaeri.cloud/1.8.8/org/bukkit/Effect.html or older docs
Particles:
  Use: true
  Type: HEART
  Amount: 1
# If you have Vault and economy plugin (like EssentialsX), you can give money to player or take from him! It's between two integers,
# so have fun with this!
Money: -20;10
# Put all your items into this section!
Contents:
  CommonSword:
    DisplayName: 'Common Sword'
    DisplayLore:
      - '&eExample Lore'
      - '&cWith custom colours!'
    Material: STONE_SWORD
    Enchantments:
      - damage_all:5
      - durability:3
    Chance: 0.5